export const Data = [
    {
        Thit_Ca_Trung: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "0",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "0",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Rau_Cu_Qua: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Gia_Vi: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Thuc_Pham_Kho: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Thuc_Uong: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Sua: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Hoa_pham: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ],
        Cham_Soc_Ca_Nhan: [
            {
                id: 0,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/frNEki7SOCgRA-8-3aY1qCDmUFqr1ehmdreM_oc5a21hsihAtelO4H0H_Xi8r5pG2hZVmml3LBQYGNUtn1c=w185",
                promotion: "4000",
            },
            {
                id: 1,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/nDzdj2x6NjLjdsgg9KWmKrvzP-GGlQh1Wr0SnyIza4HvNf24Qda39oex5JWprRHem5YMgnF2tFXn4Ah_Og=w185",
                promotion: "4000",
            },
            {
                id: 2,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/T8nj7cNMY4t4u419p4J6EYp5WpX6tpd5bOnChFPLoO6UoKEjtjjs0QtAz_AKkhoyF0oaqcTcAzyBEOtXvqq9=w185",
                promotion: "4000",
            },
            {
                id: 3,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/e-UD-aWMMOwqiOABoBjdNExbaVF55IiYNiKax3z3FhLGmv6JD7qXuvjOk6BCY0nBeT1kDS9TZOAKH2-KHe5q=w185",
                promotion: "4000",
            },
            {
                id: 4,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/31tsfG6Fn7iB_DC09-v1IPWp8OoKU-Vd9iQU0mSAC92t4WFLavSIJYqMZZCtbxTkXo0enT8tAhdMf3dHmmM=w185",
                promotion: "4000",
            },
            {
                id: 5,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/6QRJ3tz433-FvcLDS14iYi1n9kOeJL03hRZrN5roIBGLyK6jtI--CxsBw-UUiNS-AIyEbRDO4LeO5C0kyzw=w185",
                promotion: "4000",
            },
            {
                id: 6,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/v-TDcT6vBPsYarqdNv1WKBdWjgnbuW_8fpn6MNQlbP70E4fukKRrMXP1vgS8oxm1sVb_ChdOYxDbJR29AuM=w185",
                promotion: "4000",
            },
            {
                id: 7,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/rLpkBWbH1PR8_H7stHsnmCvyAjlyZuCXSCvf0TEVtlLiwBvkf5uBPL69YMyyP_APkAB3c31nKXb4AnASb3Or=w185",
                promotion: "4000",
            },
            {
                id: 8,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/Wpop5js-K9Aw6WJHuuX_mvSiX7IuW29dV6nx0JJybXBbgFLkTdx0oLvBx945PIQLTRmt7_9PAcauznaNbA=w185",
                promotion: "4000",
            },
            {
                id: 9,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/C-bdEXTHWF1LsdczNFyVzLbJ2SXPO91tygD8z8UEy_WHvCTvq8bHudwDsfr5bakShUZ8993pr7GWnSB9715O=w185",
                promotion: "4000",
            },
            {
                id: 10,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/9ysEHgSmFUi7B-VG3OAoBaugQPWSh7HBBVjRmlwMXtQ1LMPrAItANKrPmCwdrhQAM7P2KgwiVs2PuPJeySVv=w185",
                promotion: "4000",
            },
            {
                id: 11,
                name: "Cánh gà CP 500g",
                amount: "3",
                price: "59000",
                faceProduct: "https://lh3.googleusercontent.com/AfgmTAUeP5P_cLZxGicFNGbm0MgHc_bAtN6w6Ml8m0iLkZ674Czx4v2IEXul6cHzZvXo31oOTFNv7X_Ltw4=w185",
                promotion: "4000",
            }
        ]
    }
]