export const GET_ADMIN_PRODUCTS = "GET_ADMIN_PRODUCTS";
export const ADD_ADMIN_PRODUCT = "ADD_ADMIN_PRODUCT";
export const UPDATE_ADMIN_PRODUCT = "UPDATE_ADMIN_PRODUCT";
export const REMOVE_ADMIN_PRODUCT = "REMOVE_ADMIN_PRODUCT";